// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: im/app/message_service.proto

package app

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SingleMessageRequest) Reset() {
	*x = SingleMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_app_message_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMessageRequest) ProtoMessage() {}

func (x *SingleMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_app_message_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMessageRequest.ProtoReflect.Descriptor instead.
func (*SingleMessageRequest) Descriptor() ([]byte, []int) {
	return file_im_app_message_service_proto_rawDescGZIP(), []int{0}
}

type SingleMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SingleMessageResponse) Reset() {
	*x = SingleMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_app_message_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMessageResponse) ProtoMessage() {}

func (x *SingleMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_app_message_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMessageResponse.ProtoReflect.Descriptor instead.
func (*SingleMessageResponse) Descriptor() ([]byte, []int) {
	return file_im_app_message_service_proto_rawDescGZIP(), []int{1}
}

type GroupMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupMessageRequest) Reset() {
	*x = GroupMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_app_message_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessageRequest) ProtoMessage() {}

func (x *GroupMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_app_message_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessageRequest.ProtoReflect.Descriptor instead.
func (*GroupMessageRequest) Descriptor() ([]byte, []int) {
	return file_im_app_message_service_proto_rawDescGZIP(), []int{2}
}

type GroupMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupMessageResponse) Reset() {
	*x = GroupMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_app_message_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessageResponse) ProtoMessage() {}

func (x *GroupMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_app_message_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessageResponse.ProtoReflect.Descriptor instead.
func (*GroupMessageResponse) Descriptor() ([]byte, []int) {
	return file_im_app_message_service_proto_rawDescGZIP(), []int{3}
}

type ImageMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImageMessageRequest) Reset() {
	*x = ImageMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_app_message_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMessageRequest) ProtoMessage() {}

func (x *ImageMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_app_message_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMessageRequest.ProtoReflect.Descriptor instead.
func (*ImageMessageRequest) Descriptor() ([]byte, []int) {
	return file_im_app_message_service_proto_rawDescGZIP(), []int{4}
}

type ImageMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImageMessageResponse) Reset() {
	*x = ImageMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_app_message_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMessageResponse) ProtoMessage() {}

func (x *ImageMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_app_message_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMessageResponse.ProtoReflect.Descriptor instead.
func (*ImageMessageResponse) Descriptor() ([]byte, []int) {
	return file_im_app_message_service_proto_rawDescGZIP(), []int{5}
}

type FileMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileMessageRequest) Reset() {
	*x = FileMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_app_message_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMessageRequest) ProtoMessage() {}

func (x *FileMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_app_message_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMessageRequest.ProtoReflect.Descriptor instead.
func (*FileMessageRequest) Descriptor() ([]byte, []int) {
	return file_im_app_message_service_proto_rawDescGZIP(), []int{6}
}

type FileMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileMessageResponse) Reset() {
	*x = FileMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_app_message_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMessageResponse) ProtoMessage() {}

func (x *FileMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_app_message_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMessageResponse.ProtoReflect.Descriptor instead.
func (*FileMessageResponse) Descriptor() ([]byte, []int) {
	return file_im_app_message_service_proto_rawDescGZIP(), []int{7}
}

var File_im_app_message_service_proto protoreflect.FileDescriptor

var file_im_app_message_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x69, 0x63, 0x75, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x16, 0x0a, 0x14, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x69, 0x6c, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15,
	0x0a, 0x13, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd0, 0x03, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x72, 0x0a, 0x0d, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x2e, 0x69, 0x63, 0x75, 0x63,
	0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x69,
	0x63, 0x75, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x22, 0x12, 0x2f, 0x69, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x6e, 0x0a, 0x0c,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x69,
	0x63, 0x75, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x69, 0x63, 0x75, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x22, 0x11, 0x2f, 0x69, 0x6d, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x6e, 0x0a, 0x0c,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x69,
	0x63, 0x75, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x69, 0x63, 0x75, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x22, 0x11, 0x2f, 0x69, 0x6d, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x6a, 0x0a, 0x0b,
	0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x69, 0x63,
	0x75, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x69,
	0x63, 0x75, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x10, 0x2f, 0x69, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_im_app_message_service_proto_rawDescOnce sync.Once
	file_im_app_message_service_proto_rawDescData = file_im_app_message_service_proto_rawDesc
)

func file_im_app_message_service_proto_rawDescGZIP() []byte {
	file_im_app_message_service_proto_rawDescOnce.Do(func() {
		file_im_app_message_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_im_app_message_service_proto_rawDescData)
	})
	return file_im_app_message_service_proto_rawDescData
}

var file_im_app_message_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_im_app_message_service_proto_goTypes = []interface{}{
	(*SingleMessageRequest)(nil),  // 0: icuc.im.app.SingleMessageRequest
	(*SingleMessageResponse)(nil), // 1: icuc.im.app.SingleMessageResponse
	(*GroupMessageRequest)(nil),   // 2: icuc.im.app.GroupMessageRequest
	(*GroupMessageResponse)(nil),  // 3: icuc.im.app.GroupMessageResponse
	(*ImageMessageRequest)(nil),   // 4: icuc.im.app.ImageMessageRequest
	(*ImageMessageResponse)(nil),  // 5: icuc.im.app.ImageMessageResponse
	(*FileMessageRequest)(nil),    // 6: icuc.im.app.FileMessageRequest
	(*FileMessageResponse)(nil),   // 7: icuc.im.app.FileMessageResponse
}
var file_im_app_message_service_proto_depIdxs = []int32{
	0, // 0: icuc.im.app.MessageService.SingleMessage:input_type -> icuc.im.app.SingleMessageRequest
	2, // 1: icuc.im.app.MessageService.GroupMessage:input_type -> icuc.im.app.GroupMessageRequest
	4, // 2: icuc.im.app.MessageService.ImageMessage:input_type -> icuc.im.app.ImageMessageRequest
	6, // 3: icuc.im.app.MessageService.FileMessage:input_type -> icuc.im.app.FileMessageRequest
	1, // 4: icuc.im.app.MessageService.SingleMessage:output_type -> icuc.im.app.SingleMessageResponse
	3, // 5: icuc.im.app.MessageService.GroupMessage:output_type -> icuc.im.app.GroupMessageResponse
	5, // 6: icuc.im.app.MessageService.ImageMessage:output_type -> icuc.im.app.ImageMessageResponse
	7, // 7: icuc.im.app.MessageService.FileMessage:output_type -> icuc.im.app.FileMessageResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_im_app_message_service_proto_init() }
func file_im_app_message_service_proto_init() {
	if File_im_app_message_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_im_app_message_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_app_message_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_app_message_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_app_message_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_app_message_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_app_message_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_app_message_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_app_message_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_im_app_message_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_app_message_service_proto_goTypes,
		DependencyIndexes: file_im_app_message_service_proto_depIdxs,
		MessageInfos:      file_im_app_message_service_proto_msgTypes,
	}.Build()
	File_im_app_message_service_proto = out.File
	file_im_app_message_service_proto_rawDesc = nil
	file_im_app_message_service_proto_goTypes = nil
	file_im_app_message_service_proto_depIdxs = nil
}
